### ISSUE TITLE
Missing index in map.jinja

### ISSUE THREAD

**Issue by meistermild** [saltstack-formulas/openldap-formula#22]
The index is only provided in "default". I am using debian, so the "default"-block is beeing ignored. Following line is missing in "Debian"-block:

`'index': 'objectClass'`

I fixed it by adding the following to my init.sls:

```
openldap:
  lookup:
    index: objectClass
```

**Comment by sticky-note** [comment]
@Myii We can clause this issue as https://github.com/saltstack-formulas/openldap-formula/pull/24 has been merged

**Comment by myii** [comment]
@sticky-note Sure, thanks.  @meistermild Please pull the latest version of the formula to get the defaults working properly.
