### ISSUE TITLE
Jinja variable 'rootdn' is undefined

### ISSUE THREAD

**Issue by hemebond** [saltstack-formulas/openldap-formula#6]
init.sls defines the Jinja variable rootpw but then checks for rootdn.

**Comment by puneetk** [comment]
@hemebond send pull request with fixes, thanks for finding the issue and reporting it.

**Comment by gravyboat** [comment]
@hemebond I fixed this over in #7.

**Comment by puneetk** [comment]
in a race to click buttons there is no winners , :+1:  @gravyboat

**Comment by gravyboat** [comment]
I'm honestly impressed it didn't just error.
